<?php
return <<<DATA
   <goodsDeclareDetail>
            <goodsOrder>%s</goodsOrder>
            <codeTs>%s</codeTs>
            <goodsItemNo>%s</goodsItemNo>
            <goodsName>%s</goodsName>
            <goodsModel>%s</goodsModel>
            <originCountry>%s</originCountry>
            <tradeCurr>%s</tradeCurr>
            <tradeTotal>%s</tradeTotal>
            <declPrice>%s</declPrice>
            <declTotalPrice>%s</declTotalPrice>
            <useTo>%s</useTo>
            <declareCount>%s</declareCount>
            <goodsUnit>%s</goodsUnit>
            <goodsGrossWeight>%s</goodsGrossWeight>
            <firstUnit>%s</firstUnit>
            <firstCount>%s</firstCount>
            <secondUnit>%s</secondUnit>
            <secondCount>%s</secondCount>
			<productRecordNo>%s</productRecordNo>
			<webSite>%s</webSite>
</goodsDeclareDetail>
DATA;
?>