<?php
return <<<DATA
        <goodsDeclare>
  <accountBookNo>%s</accountBookNo>
          <ieFlag>%s</ieFlag>
          <preEntryNumber>%s</preEntryNumber>
          <importType>%s</importType>
          <inOutDateStr>%s</inOutDateStr>
          <iePort>%s</iePort>
          <destinationPort>%s</destinationPort>
          <trafName>%s</trafName>
          <voyageNo>%s</voyageNo>
          <trafMode>%s</trafMode>
          <declareCompanyType>%s</declareCompanyType>
          <declareCompanyCode>%s</declareCompanyCode>
          <declareCompanyName>%s</declareCompanyName>
          <eCommerceCode>%s</eCommerceCode>
          <eCommerceName>%s</eCommerceName>
          <orderNo>%s</orderNo>
          <wayBill>%s</wayBill>
          <tradeCountry>%s</tradeCountry>
          <packNo>%s</packNo>
          <grossWeight>%s</grossWeight>
          <netWeight>%s</netWeight>
          <warpType>%s</warpType>
          <remark>%s</remark>
          <declPort>%s</declPort>
          <enteringPerson>%s</enteringPerson>
          <enteringCompanyName>%s</enteringCompanyName>
          <declarantNo>%s</declarantNo>
          <customsField>%s</customsField>
          <senderName>%s</senderName>
          <consignee>%s</consignee>
          <senderCountry>%s</senderCountry>
          <senderCity>%s</senderCity>
          <paperType>%s</paperType>
          <paperNumber>%s</paperNumber>
          <worth>%s</worth>
          <currCode>%s</currCode>
          <mainGName>%s</mainGName>
          <internalAreaCompanyNo>%s</internalAreaCompanyNo>
        <internalAreaCompanyName>%s</internalAreaCompanyName>
          <applicationFormNo>%s</applicationFormNo>
<isAuthorize>%s</isAuthorize>
        </goodsDeclare>
DATA;
?>